declare type ModActions = 'BAN' | 'UNBAN' | 'SOFTBAN' | 'KICK' | 'MUTE' | 'UNMUTE' | 'WARN' | 'PARDON'

declare type EventActions = 'MESSAGE_UPDATED' | 'MESSAGE_DELETED' | 'MESSAGE_BULK_DELETED' | 'CHANNEL_CREATED' | 'CHANNEL_UPDATED' | 'CHANNEL_DELETED' | 'ROLE_CREATED' |
    'ROLE_UPDATED' | 'ROLE_DELETED' | 'GUILD_UPDATED' | 'INVITE_CREATED' | 'INVITE_DELETED' | 'USER_UPDATED' | 'GUILD_MEMBER_ADD' | 'GUILD_MEMBER_REMOVE' | 'GUILD_MEMBER_UPDATED'