import { ColorResolvable } from 'discord.js'

export const Colors = {
	White: '#ffffff' as ColorResolvable,
	Black: '#000000' as ColorResolvable,
	PowderBlue: '#b0e0e6' as ColorResolvable,
	Cyan: '#00ffff' as ColorResolvable,
	SkyBlue: '#7ec0ee' as ColorResolvable,
	SteelBlue: '#4682b4' as ColorResolvable,
	Turquoise: '#40e0d0' as ColorResolvable,
	IndianRed: '#cd5c5c' as ColorResolvable,
	Pink: '#ffc0cb' as ColorResolvable,
	HotPink: '#ff69b4' as ColorResolvable,
	Violet: '#ee82ee' as ColorResolvable,
	Pinky: '#ea8cff' as ColorResolvable,
	Plum: '#dda0dd' as ColorResolvable,
	GoldenRod: '#daa520' as ColorResolvable,
	Golden: '#ffd700' as ColorResolvable,
	Yellow: '#ffff00' as ColorResolvable,
	Supernova: '#ffac33' as ColorResolvable,
	Orange: '#ffa500' as ColorResolvable,
	DarkOrange: '#ff8c00' as ColorResolvable,
	Coral: '#ff6347' as ColorResolvable,
	Tomato: '	#ff4500' as ColorResolvable,
	Purple: '#551a8b' as ColorResolvable,
	Red: '#ff0000' as ColorResolvable,
	Crimson: '#dc143c' as ColorResolvable,
	Spring: '#00ff7f' as ColorResolvable,
	Lime: '#bfff00' as ColorResolvable,
	Green: '#339933' as ColorResolvable,
	DarkGreen: '#24705d' as ColorResolvable,
	SeaGreen: '#9fe2bf' as ColorResolvable,
	Mint: '#99ff99' as ColorResolvable,
	BrandPink: '#c92598' as ColorResolvable,
	NovaGreen: '#3cb371' as ColorResolvable,
	AeonBrown: '#a16a6a' as ColorResolvable,
	SlateGray: '#708090' as ColorResolvable,
	Blurple: '#5865f2' as ColorResolvable,
	BlueViolet: '#7c3aed' as ColorResolvable,
	Active: '#57f287' as ColorResolvable,
	HighlightYellow: '#fee75c' as ColorResolvable,
	Fuchsia: '#eb459e' as ColorResolvable,
	Critical: '#ed4245' as ColorResolvable,
	CatRed: '#FF6B6B' as ColorResolvable,
	DogTeal: '#4ECDC4' as ColorResolvable,
	BunnyPink: '#FFB6C1' as ColorResolvable,
	FoxOrange: '#FF8C42' as ColorResolvable
}
